joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

egm_state_controller:
  type         : abb_egm_state_controller/EGMStateController
  publish_rate : 250

# These settings must match:
# - Joint names extracted from the ABB robot controller.
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6


joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6


# joint_trajectory_controller:
#   type: velocity_controllers/JointTrajectoryController
#   joints:
#     - joint_1
#     - joint_2
#     - joint_3
#     - joint_4
#     - joint_5
#     - joint_6

#   constraints:
#     goal_time: 0.6
#     stopped_velocity_tolerance: 0.1
#     joint_1: {trajectory: 0.1, goal: 0.2}
#     joint_2: {trajectory: 0.1, goal: 0.2}
#     joint_3: {trajectory: 0.1, goal: 0.2}
#     joint_4: {trajectory: 0.1, goal: 0.2}
#     joint_5: {trajectory: 0.1, goal: 0.2}
#     joint_6: {trajectory: 0.1, goal: 0.2}

#   gains:
#     joint_1: {p: 15, i: 0.05, d: 0.001}
#     joint_2: {p: 15, i: 0.05, d: 0.001}
#     joint_3: {p: 15, i: 0.05, d: 0.001}
#     joint_4: {p: 20, i: 0.12, d: 0.001, i_clamp_max: 0.2}
#     joint_5: {p: 20, i: 0.12, d: 0.001, i_clamp_max: 0.2}
#     joint_6: {p: 20, i: 0.12, d: 0.001, i_clamp_max: 0.2}

joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 1
    # joint_1: {trajectory: 0.004, goal: 0.002}
    # joint_2: {trajectory: 0.004, goal: 0.002}
    # joint_3: {trajectory: 0.004, goal: 0.002}
    # joint_4: {trajectory: 0.004, goal: 0.002}
    # joint_5: {trajectory: 0.004, goal: 0.002}
    # joint_6: {trajectory: 0.004, goal: 0.002}

    joint_1: {trajectory: 0.1, goal: 0.001}
    joint_2: {trajectory: 0.1, goal: 0.001}
    joint_3: {trajectory: 0.1, goal: 0.001}
    joint_4: {trajectory: 0.1, goal: 0.001}
    joint_5: {trajectory: 0.1, goal: 0.001}
    joint_6: {trajectory: 0.1, goal: 0.001}
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

compliance_controller:
  type: "velocity_controllers/CartesianComplianceController"
  end_effector_link: "tool0"    # All links below must come before this link
  robot_base_link: "base_link"
  ft_sensor_ref_link: "tool0"
  compliance_ref_link: "tool0"
  target_frame_topic: "tool0"
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  stiffness:  # w.r.t. compliance_ref_link
    trans_x: 10
    trans_y: 10
    trans_z: 10
    rot_x: 100
    rot_y: 100
    rot_z: 100

  pd_gains:
      trans_x: {p: 0.01}
      trans_y: {p: 0.01}
      trans_z: {p: 0.01}
      rot_x: {p: 0.01}
      rot_y: {p: 0.01}
      rot_z: {p: 0.01}

force_controller:
  type: "velocity_controllers/CartesianForceController"
  end_effector_link: "tool0"
  robot_base_link: "base_link"
  ft_sensor_ref_link: "tool0"
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  pd_gains:
      trans_x: {p: 0.5}
      trans_y: {p: 0.5}
      trans_z: {p: 0.5}
      rot_x: {p: 0.00}
      rot_y: {p: 0.00}
      rot_z: {p: 0.00}
